### ISSUE TITLE
GET / composition FLAT error with NSS RESPECT

### ISSUE THREAD

**Issue by freshehr** [ethercis/ethercis#179]
[RESPECT_NSS-v0.zip](https://github.com/ethercis/ethercis/files/3025770/RESPECT_NSS-v0.zip) - related .opt
```
{
  "ctx/language": "en",
  "ctx/territory": "GB",
  "nss_respect_form/language|code": "en",
  "nss_respect_form/language|terminology": "ISO_639-1",
  "nss_respect_form/territory|code": "GB",
  "nss_respect_form/territory|terminology": "ISO_3166-1",
  "nss_respect_form/context/_health_care_facility|id": "FV-DGH",
  "nss_respect_form/context/_health_care_facility|id_scheme": "NHSScotland",
  "nss_respect_form/context/_health_care_facility|id_namespace": "NHSScotland",
  "nss_respect_form/context/_health_care_facility|name": "Forth Valley DGH",
  "nss_respect_form/context/start_time": "2019-03-03T23:09:53.121+01:00",
  "nss_respect_form/context/setting|code": "238",
  "nss_respect_form/context/setting|value": "other care",
  "nss_respect_form/context/setting|terminology": "openehr",
  "nss_respect_form/context/status": "",
  "nss_respect_form/composer|name": "Bobbie Tweed",
  "nss_respect_form/composer|id": "12345",
  "nss_respect_form/composer|id_scheme": "NHSScotland",
  "nss_respect_form/composer|id_namespace": "NHSScotland",
  "nss_respect_form/respect_headings/a2._summary_of_relevant_information/a2.0_relevant_information/respect_summary/narrative_summary": "No bad thanks",
  "nss_respect_form/respect_headings/a3._personal_preferences/preferred_priorities_of_care/patient_care_priority": "",
  "nss_respect_form/respect_headings/a4._clinical_recommendations/recommendation/clinical_focus": "",
  "nss_respect_form/respect_headings/a4._clinical_recommendations/recommendation/clinical_guidance_on_interventions": "",
  "nss_respect_form/respect_headings/a4._clinical_recommendations/cpr_decision/cpr_decision|code": "",
  "nss_respect_form/respect_headings/a4._clinical_recommendations/cpr_decision/date_of_cpr_decision": "2019-03-03T23:09:53.121+01:00",
  "nss_respect_form/respect_headings/a5._capacity_and_representation/capacity_respect/sufficient_capacity": "Error running: toBoolean('')",
  "nss_respect_form/respect_headings/a5._capacity_and_representation/capacity_respect/legal_proxy|code": "",
  "nss_respect_form/respect_headings/a6._involvement_in_making_plan/involvement_respect/involvement_in_recommendations/involvement|code": "",
  "nss_respect_form/respect_headings/a6._involvement_in_making_plan/involvement_respect/involvement_in_recommendations/reason_for_not_selecting_options_a_or_b_or_c": "",
  "nss_respect_form/respect_headings/a6._involvement_in_making_plan/involvement_respect/name_and_role_of_those_involved_in_decision_making": "",
  "nss_respect_form/respect_headings/a7._clinician_signatures/clinician_signature:0/ism_transition/current_state|value": "completed",
  "nss_respect_form/respect_headings/a7._clinician_signatures/clinician_signature:0/service_name": "ReSPECT clinician signature",
  "nss_respect_form/respect_headings/a7._clinician_signatures/clinician_signature:0/signing_clinician/practitioner_role/designation": "",
  "nss_respect_form/respect_headings/a7._clinician_signatures/clinician_signature:0/signing_clinician/name/use|code": "at0002",
  "nss_respect_form/respect_headings/a7._clinician_signatures/clinician_signature:0/signing_clinician/text": "",
  "nss_respect_form/respect_headings/a7._clinician_signatures/clinician_signature:0/signing_clinician/identifier/value": "1234",
  "nss_respect_form/respect_headings/a7._clinician_signatures/clinician_signature:0/signing_clinician/identifier/value|issuer": "ProfessionalID",
  "nss_respect_form/respect_headings/a7._clinician_signatures/clinician_signature:0/signing_clinician/identifier/value|assigner": "ProfessionalID",
  "nss_respect_form/respect_headings/a7._clinician_signatures/clinician_signature:0/signing_clinician:0/identifier/value|type": "ProfessionalID",
  "nss_respect_form/respect_headings/a7._clinician_signatures/clinician_signature:0/signing_clinician:0/identifier/use|code": "at0004",
  "nss_respect_form/respect_headings/a7._clinician_signatures/clinician_signature:0/time": "2019-03-03T23:09:53.121+01:00",
  "nss_respect_form/respect_headings/a8._emergency_contacts/emergency_contacts/name": "ReSPECT emergency contacts",
  "nss_respect_form/respect_headings/a8._emergency_contacts/emergency_contacts/participant:0/role": "",
  "nss_respect_form/respect_headings/a8._emergency_contacts/emergency_contacts/participant:0/contact/name/use|code": "",
  "nss_respect_form/respect_headings/a8._emergency_contacts/emergency_contacts/participant:0/contact/name:0/text": "",
  "nss_respect_form/respect_headings/a8._emergency_contacts/emergency_contacts/participant:0/contact/telephone/system|code": "",
  "nss_respect_form/respect_headings/a8._emergency_contacts/emergency_contacts/participant:0/contact/telephone/telephone_number": "",
  "nss_respect_form/respect_headings/a8._emergency_contacts/emergency_contacts/other_details": "",
  "nss_respect_form/respect_headings/a9._confirmation_of_validity/service:0/service_name": "Respect form - confirmation of validity",
  "nss_respect_form/respect_headings/a9._confirmation_of_validity/service:0/ism_transition/current_state|value": "completed",
  
  "nss_respect_form/respect_headings/a9._confirmation_of_validity/service:0/responsible_clinician/practitioner_role/designation": "",
  "nss_respect_form/respect_headings/a9._confirmation_of_validity/service:0/responsible_clinician/name/use|code": "",
  "nss_respect_form/respect_headings/a9._confirmation_of_validity/service:0/responsible_clinician/name/text": "",
  "nss_respect_form/respect_headings/a9._confirmation_of_validity/service:0/responsible_clinician/identifier/value": "1234",
  "nss_respect_form/respect_headings/a9._confirmation_of_validity/service:0/responsible_clinician/identifier/value|issuer": "ProfessionalID",
  "nss_respect_form/respect_headings/a9._confirmation_of_validity/service:0/responsible_clinician/identifier/value|assigner": "ProfessionalID",
  "nss_respect_form/respect_headings/a9._confirmation_of_validity/service:0/responsible_clinician/identifier/value|type": "ProfessionalID",
  "nss_respect_form/respect_headings/a9._confirmation_of_validity/service:0/responsible_clinician/identifier/use|code": "at0004",
  "nss_respect_form/respect_headings/a9._confirmation_of_validity/service:0/review_date": "",
  "nss_respect_form/respect_headings/a9._confirmation_of_validity/service:0/time": "2019-03-03T23:09:53.121+01:00"
}
```
Did succesful POST, then PUT of this data, .
[RESPECT_NSS-v0.zip](https://github.com/ethercis/ethercis/files/3025732/RESPECT_NSS-v0.zip)
opt attached.

Result
{
    "compositionUid": "f1154e54-f326-4f2a-a334-d9f002a76501::nes.ripple.foundation::2",
    "meta": {
        "href": "rest/v1/composition?uid=f1154e54-f326-4f2a-a334-d9f002a76501::nes.ripple.foundation::1"
    },
    "action": "UPDATED"
}

If I do GET with root CompositionID (or with full versioned composition), RAW format , it works, but with FLAT format I get

```
curl -X GET \
  'http://ethercis1.3-test.ripple.foundation:8080/rest/v1/composition/f1154e54-f326-4f2a-a334-d9f002a76501?format=FLAT' \
  -H 'Authorization: Basic Z3Vlc3Q6Z3Vlc3Q=' \
  -H 'Content-Type: application/json' \
  -H 'Ehr-Session: sessionId:127.0.0.1-guest-1553964745395-1015751736-9' \
```

```
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
        <title>Error 500 #1.0.0 Invocation exception to method:retrieve:javax.xml.bind.UnmarshalException: Unable to create an instance of org.openehr.jaxb.rm.ItemStructure
 - with linked exception:
[java.lang.InstantiationException]</title>
    </head>
    <body>
        <h2>HTTP ERROR 500</h2>
        <p>Problem accessing /rest/v1/composition/f1154e54-f326-4f2a-a334-d9f002a76501. Reason:

            <pre>    #1.0.0 Invocation exception to method:retrieve:javax.xml.bind.UnmarshalException: Unable to create an instance of org.openehr.jaxb.rm.ItemStructure
 - with linked exception:
[java.lang.InstantiationException]</pre>
        </p>
        <hr>
        <a href="http://eclipse.org/jetty">Powered by Jetty:// 9.4.z-SNAPSHOT</a>
        <hr/>
    </body>
</html>
```
works correctly on Think!Ehr.

**Comment by chevalleyc** [comment]
Seems that `ITEM_STRUCTURE` is not supported by Marand's library: thinkehr-framework-jsonlib-2.3.0-JL32.jar (2.3.0-JL32 (29th Feb, 2016)).

Decompiled org.openehr.jaxb.rm.ItemStructure :

```
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "ITEM_STRUCTURE"
)
@XmlSeeAlso({ItemSingle.class, ItemTree.class, ItemList.class, ItemTable.class})
public abstract class ItemStructure extends Locatable implements Serializable {
    private static final long serialVersionUID = 0L;

    public ItemStructure() {
    }
}
```
whereas ItemTree is 
```
XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "ITEM_TREE",
    propOrder = {"items"}
)
public class ItemTree extends ItemStructure implements Serializable {
    private static final long serialVersionUID = 0L;
    protected List<Item> items;

    public ItemTree() {
    }

    public List<Item> getItems() {
        if (this.items == null) {
            this.items = new ArrayList();
        }

        return this.items;
    }
}
```
Unfortunately, as it is closed source, I cannot investigate further nor recompile it

**Comment by freshehr** [comment]
@chevalleyc This is very odd. It works ok on ThinkEhr and there are no instances of ITEM_STRUCTURE in the .opt or xml serialisation that I can find. Can you tell me where you are encountering an ITEM_STRUCTURE in the instance?

**Comment by chevalleyc** [comment]
@freshehr It might be implicit, here is the full stack trace of the invocation of fromComposition:

```
javax.xml.bind.UnmarshalException: Unable to create an instance of org.openehr.jaxb.rm.ItemStructure
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallingContext.handleEvent(UnmarshallingContext.java:714) ~[ethercis-1.3.0-SNAPSHOT-runtime.jar:?]
	at com.sun.xml.bind.v2.runtime.unmarshaller.Loader.reportError(Loader.java:232) ~[ethercis-1.3.0-SNAPSHOT-runtime.jar:?]
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallingContext.createInstance(UnmarshallingContext.java:678) ~[ethercis-1.3.0-SNAPSHOT-runtime.jar:?]
	at com.sun.xml.bind.v2.runtime.unmarshaller.StructureLoader.startElement(StructureLoader.java:158) ~[ethercis-1.3.0-SNAPSHOT-runtime.jar:?]
	at com.sun.xml.bind.v2.runtime.unmarshaller.XsiTypeLoader.startElement(XsiTypeLoader.java:50) ~[ethercis-1.3.0-SNAPSHOT-runtime.jar:?]
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallingContext._startElement(UnmarshallingContext.java:547) ~[ethercis-1.3.0-SNAPSHOT-runtime.jar:?]
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallingContext.startElement(UnmarshallingContext.java:526) ~[ethercis-1.3.0-SNAPSHOT-runtime.jar:?]
	at com.sun.xml.bind.v2.runtime.unmarshaller.SAXConnector.startElement(SAXConnector.java:138) ~[ethercis-1.3.0-SNAPSHOT-runtime.jar:?]
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509) ~[?:1.8.0_191]
	at com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(AbstractXMLDocumentParser.java:182) ~[?:1.8.0_191]
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:351) ~[?:1.8.0_191]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2784) ~[?:1.8.0_191]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602) ~[?:1.8.0_191]
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112) ~[?:1.8.0_191]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505) ~[?:1.8.0_191]
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842) ~[?:1.8.0_191]
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771) ~[?:1.8.0_191]
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141) ~[?:1.8.0_191]
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213) ~[?:1.8.0_191]
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643) ~[?:1.8.0_191]
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:228) ~[ethercis-1.3.0-SNAPSHOT-runtime.jar:?]
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:199) ~[ethercis-1.3.0-SNAPSHOT-runtime.jar:?]
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:157) ~[?:1.8.0_191]
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:214) ~[?:1.8.0_191]
	at com.ethercis.ehr.util.FlatJsonCompositionConverter.fromComposition(FlatJsonCompositionConverter.java:171) ~[ethercis-1.3.0-SNAPSHOT-runtime.jar:?]
```

**Comment by chevalleyc** [comment]
Let me check this further...

**Comment by chevalleyc** [comment]
Definitely something fishy with this template as I have run a test with others including the previous RESPECT_form_2-v0. RESPECT_NSS-v0 consistently fails. In  doubt, I have also tried to use the 'old' jaxb binding from Oracle instead of Glassfish, but the result is the same. Could be a good idea to ask the maintainer (Marand) to have a look...

**Comment by freshehr** [comment]
@Christian - so the older template 'RESPECT_form_2-v0' works? Just to confirm is that jaxb error occurring inside the Marand library?

**Comment by chevalleyc** [comment]
Yes, the older one can be retrieved with FLAT. 

The unmarshalling issue is from within the Marand library

**Comment by freshehr** [comment]
Thx @chevalleyc - I have initiated conversation with Marand. I did notice something interesting about the commit. I tried to save a very minimum composition

```
{
  "ctx/language": "en",
  "ctx/territory": "GB",
  "nss_respect_form/language|code": "en",
  "nss_respect_form/language|terminology": "ISO_639-1",
  "nss_respect_form/territory|code": "GB",
  "nss_respect_form/territory|terminology": "ISO_3166-1",
  "nss_respect_form/context/_health_care_facility|id": "FV-DGH",
  "nss_respect_form/context/_health_care_facility|id_scheme": "NHSScotland",
  "nss_respect_form/context/_health_care_facility|id_namespace": "NHSScotland",
  "nss_respect_form/context/_health_care_facility|name": "Forth Valley DGH",
  "nss_respect_form/context/start_time": "2019-03-03T23:09:53.121+01:00",
  "nss_respect_form/context/setting|code": "238",
  "nss_respect_form/context/setting|value": "other care",
  "nss_respect_form/context/setting|terminology": "openehr",
  "nss_respect_form/context/status": "",
  "nss_respect_form/composer|name": "Bobbie McTweed",
  "nss_respect_form/composer|id": "1234567",
  "nss_respect_form/composer|id_scheme": "NHSScotland",
  "nss_respect_form/composer|id_namespace": "NHSScotland"
 
}
```

which fails on a GET FLAT but retunrs this on GET RAW XML

```
<composition xmlns="http://schemas.openehr.org/v1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" archetype_node_id="openEHR-EHR-COMPOSITION.report.v1">
    <name>
        <value>NSS RESPECT Form</value>
    </name>
    <uid xmlns:v1="http://schemas.openehr.org/v1" xsi:type="v1:OBJECT_VERSION_ID">
        <value>91c01653-ad16-45d8-9740-b99c6771ad60::nes.ripple.foundation::1</value>
    </uid>
    <archetype_details>
        <archetype_id>
            <value>openEHR-EHR-COMPOSITION.report.v1</value>
        </archetype_id>
        <template_id>
            <value>RESPECT_NSS-v0</value>
        </template_id>
        <rm_version>1.0.1</rm_version>
    </archetype_details>
    <language>
        <terminology_id>
            <value>ISO_639-1</value>
        </terminology_id>
        <code_string>en</code_string>
    </language>
    <territory>
        <terminology_id>
            <value>ISO_3166-1</value>
        </terminology_id>
        <code_string>GB</code_string>
    </territory>
    <category>
        <value>event</value>
        <defining_code>
            <terminology_id>
                <value>openehr</value>
            </terminology_id>
            <code_string>433</code_string>
        </defining_code>
    </category>
    <composer xmlns:v1="http://schemas.openehr.org/v1" xsi:type="v1:PARTY_IDENTIFIED">
        <external_ref>
            <id xsi:type="v1:GENERIC_ID">
                <value>1234567</value>
                <scheme>NHSScotland</scheme>
            </id>
            <namespace>NHSScotland</namespace>
            <type>ANY</type>
        </external_ref>
        <name>Bobbie McTweed</name>
    </composer>
    <context>
        <start_time>
            <value>2019-03-03T23:09:53.121+01:00</value>
        </start_time>
        <setting>
            <value>other care</value>
            <defining_code>
                <terminology_id>
                    <value>openehr</value>
                </terminology_id>
                <code_string>238</code_string>
            </defining_code>
        </setting>
        <health_care_facility>
            <external_ref>
                <id xmlns:v1="http://schemas.openehr.org/v1" xsi:type="v1:GENERIC_ID">
                    <value>FV-DGH</value>
                    <scheme>NHSScotland</scheme>
                </id>
                <namespace>NHSScotland</namespace>
                <type>PARTY</type>
            </external_ref>
            <name>Forth Valley DGH</name>
        </health_care_facility>
    </context>
    <content xmlns:v1="http://schemas.openehr.org/v1" archetype_node_id="openEHR-EHR-SECTION.respect_headings.v0" xsi:type="v1:SECTION">
        <name>
            <value>ReSPECT headings</value>
        </name>
        <archetype_details>
            <archetype_id>
                <value>openEHR-EHR-SECTION.respect_headings.v0</value>
            </archetype_id>
            <rm_version>1.0.1</rm_version>
        </archetype_details>
        <items archetype_node_id="at0008" xsi:type="v1:SECTION">
            <name>
                <value>5. Capacity and representation</value>
            </name>
            <items archetype_node_id="openEHR-EHR-ADMIN_ENTRY.capacity_respect.v0" xsi:type="v1:ADMIN_ENTRY">
                <name>
                    <value>Capacity ReSPECT</value>
                </name>
                <archetype_details>
                    <archetype_id>
                        <value>openEHR-EHR-ADMIN_ENTRY.capacity_respect.v0</value>
                    </archetype_id>
                    <template_id>
                        <value>RESPECT_NSS-v0</value>
                    </template_id>
                    <rm_version>1.0.1</rm_version>
                </archetype_details>
                <language>
                    <terminology_id>
                        <value>ISO_639-1</value>
                    </terminology_id>
                    <code_string>en</code_string>
                </language>
                <encoding>
                    <terminology_id>
                        <value>IANA_character-sets</value>
                    </terminology_id>
                    <code_string>UTF-8</code_string>
                </encoding>
                <subject xsi:type="v1:PARTY_SELF"/>
                <data xsi:nil="true"/>
            </items>
        </items>
        <items archetype_node_id="at0009" xsi:type="v1:SECTION">
            <name>
                <value>6. Involvement in making plan</value>
            </name>
            <items archetype_node_id="openEHR-EHR-ADMIN_ENTRY.involvement_respect.v0" xsi:type="v1:ADMIN_ENTRY">
                <name>
                    <value>Involvement ReSPECT</value>
                </name>
                <archetype_details>
                    <archetype_id>
                        <value>openEHR-EHR-ADMIN_ENTRY.involvement_respect.v0</value>
                    </archetype_id>
                    <template_id>
                        <value>RESPECT_NSS-v0</value>
                    </template_id>
                    <rm_version>1.0.1</rm_version>
                </archetype_details>
                <language>
                    <terminology_id>
                        <value>ISO_639-1</value>
                    </terminology_id>
                    <code_string>en</code_string>
                </language>
                <encoding>
                    <terminology_id>
                        <value>IANA_character-sets</value>
                    </terminology_id>
                    <code_string>UTF-8</code_string>
                </encoding>
                <subject xsi:type="v1:PARTY_SELF"/>
                <data xsi:nil="true"/>
            </items>
        </items>
        <items archetype_node_id="at0011" xsi:type="v1:SECTION">
            <name>
                <value>8. Emergency contacts</value>
            </name>
            <items archetype_node_id="openEHR-EHR-ADMIN_ENTRY.careteam_cc.v0" xsi:type="v1:ADMIN_ENTRY">
                <name>
                    <value>Emergency contacts</value>
                </name>
                <archetype_details>
                    <archetype_id>
                        <value>openEHR-EHR-ADMIN_ENTRY.careteam_cc.v0</value>
                    </archetype_id>
                    <template_id>
                        <value>RESPECT_NSS-v0</value>
                    </template_id>
                    <rm_version>1.0.1</rm_version>
                </archetype_details>
                <language>
                    <terminology_id>
                        <value>ISO_639-1</value>
                    </terminology_id>
                    <code_string>en</code_string>
                </language>
                <encoding>
                    <terminology_id>
                        <value>IANA_character-sets</value>
                    </terminology_id>
                    <code_string>UTF-8</code_string>
                </encoding>
                <subject xsi:type="v1:PARTY_SELF"/>
                <data xsi:nil="true"/>
            </items>
        </items>
    </content>
</composition>
```

As you can see a number of ADMIN_ENTRY instances are being created, which is oncorrect as these are essentially empty entries - I wonder if that is the root of the problem we are seeing?

This is what ThinkEHR returns
```
   <composition xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="COMPOSITION" archetype_node_id="openEHR-EHR-COMPOSITION.report.v1">
        <name>
            <value>NSS RESPECT Form</value>
        </name>
        <uid xsi:type="OBJECT_VERSION_ID">
            <value>366b8efb-2bee-4a64-ab6c-4f06bc431691::92aac94f-47f7-46fd-8e25-2c41da92698e::1</value>
        </uid>
        <archetype_details>
            <archetype_id>
                <value>openEHR-EHR-COMPOSITION.report.v1</value>
            </archetype_id>
            <template_id>
                <value>RESPECT_NSS-v0</value>
            </template_id>
            <rm_version>1.0.1</rm_version>
        </archetype_details>
        <language>
            <terminology_id>
                <value>ISO_639-1</value>
            </terminology_id>
            <code_string>en</code_string>
        </language>
        <territory>
            <terminology_id>
                <value>ISO_3166-1</value>
            </terminology_id>
            <code_string>GB</code_string>
        </territory>
        <category>
            <value>event</value>
            <defining_code>
                <terminology_id>
                    <value>openehr</value>
                </terminology_id>
                <code_string>433</code_string>
            </defining_code>
        </category>
        <composer xsi:type="PARTY_IDENTIFIED">
            <external_ref>
                <id xsi:type="GENERIC_ID">
                    <value>1234567</value>
                    <scheme>NHSScotland</scheme>
                </id>
                <namespace>NHSScotland</namespace>
                <type>ANY</type>
            </external_ref>
            <name>Bobbie McTweed</name>
        </composer>
        <context>
            <start_time>
                <value>2019-03-03T23:09:53.121+01:00</value>
            </start_time>
            <setting>
                <value>other care</value>
                <defining_code>
                    <terminology_id>
                        <value>openehr</value>
                    </terminology_id>
                    <code_string>238</code_string>
                </defining_code>
            </setting>
            <health_care_facility>
                <external_ref>
                    <id xsi:type="GENERIC_ID">
                        <value>FV-DGH</value>
                        <scheme>NHSScotland</scheme>
                    </id>
                    <namespace>NHSScotland</namespace>
                    <type>ANY</type>
                </external_ref>
                <name>Forth Valley DGH</name>
            </health_care_facility>
        </context>
    </composition>
```

**Comment by chevalleyc** [comment]
Good news! Eliminating Admin entries with nil data fixed the unmarshalling issue. I've updated the test server and could retrieve a composition under FLAT.
