### ISSUE TITLE
Possible concurrency errors reading composition

### ISSUE THREAD

**Issue by grantforrester-nes** [ethercis/ethercis#195]
We are using Ethercis v1.3 and are seeing intermittent status code 500 errors returned from Ethercis when retrieving a single composition from concurrent threads.

When each error occurs the Ethercis log file contains the following stacktrace:

`
[qtp706197430-119] WARN org.eclipse.jetty.server.HttpChannel - /rest/v1/composition/1daf820c-4982-4509-a059-fd7f464ea40d%3A%3Alocal.ethercis.com%3A%3A1
java.lang.IllegalArgumentException: Unhandled data type in response return
	at com.ethercis.vehr.VEhrGateServlet.handleOutput(VEhrGateServlet.java:837)
	at com.ethercis.vehr.VEhrGateServlet.syncExecute(VEhrGateServlet.java:660)
	at com.ethercis.vehr.VEhrGateServlet.processRequest(VEhrGateServlet.java:626)
	at com.ethercis.vehr.VEhrGateServlet.doGet(VEhrGateServlet.java:449)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        ...
`

We have been able to reproduce this in a unit test which can be seen here -> https://github.com/grantforrester-nes/ethercis-test-suite/blob/master/src/test/java/EthercisReadTests.java#L44

Could you advise if we are using Ethercis correctly? Is this a known problem? Any help very much appreciated.

**Comment by chevalleyc** [comment]
I think this issue is related to Jetty under load. Perhaps, you try to tweak its behaviour by setting parameters in services.properties (see https://github.com/ethercis/deploy-n-scripts/blob/master/ethercis-install/v1.3.0/config/services.properties) and Jetty doc at: https://www.eclipse.org/jetty/documentation/

Btw I remember experiencing similar issue when running it under Windows, but not sure of the context...

**Comment by grantforrester-nes** [comment]
Thanks for your reply.
We are running in a Debian 8 Docker container.

I was able to connect to the running service and debug through code.  I think the problem seems to be with `getGlobal().getProperty().get(MethodName.RETURN_TYPE_PROPERTY)` and if `getGlobal().getProperty().set(MethodName.RETURN_TYPE_PROPERTY, ...)` being read and over-written by different threads.  It looks like... 

1. During processing a request CompositionService:283 sets global state from the ‘format’ request parameter

`global.getProperty().set(MethodName.RETURN_TYPE_PROPERTY, "" + MethodName.RETURN_JSON);`

2. Later in request processing VEhrServlet:810 reads global state and resets parameter `returnType.`

```
if (getGlobal().getProperty().propertyExists(MethodName.RETURN_TYPE_PROPERTY)) {
  int changedType = getGlobal().getProperty().get(MethodName.RETURN_TYPE_PROPERTY, MethodName.RETURN_UNDEFINED);
  if (changedType != MethodName.RETURN_UNDEFINED)
    returnType = changedType;
}
```

3. In same method, after writing response, VEhrServlet:865 resets global state.

`global.getProperty().set(MethodName.RETURN_TYPE_PROPERTY, "" + MethodName.RETURN_UNDEFINED);`
 
My theory is one thread is clobbering the global state for another as follows:

1. Request A arrives
2. Request A sets global property `return.type.property` to `RETURN_JSON` at CompositionService:283
3. Request A enters VEHRServlet.handleOutput with param returnType = `RETURN_STRING`
4. Request A gets global property`return.type.property` and receives `RETURN_JSON` at VEhrServlet:810
5. Request A resets `returnType` parameter to `RETURN_JSON`
6.  _Request B arrives_
7.  _Request B sets global property `return.type.property` to `RETURN_JSON`_ at CompositionService:283
8. Request A writes JSON to output
9. Request A resets global property `return.type.property` to **`RETURN_UNDEFINED`** at VEhrServlet:865   **<----- BAD FOR REQUEST B**
10. Request A leaves
11. _Request B enters VEHRServlet.handleOutput with param returnType = `RETURN_STRING`_
12. _Request B gets global property `return.type.property` and receives **`RETURN_UNDEFINED`**_ at VEhrServlet:810
13. _Request B keeps `returnType` = `RETURN_STRING`_
14. _Request B enters `case: RETURN_STRING`_
15. _Request B throws IllegalArgumentException because output is of type HashMap (its a composition)_

Do you think this global state might be the problem?

**Comment by chevalleyc** [comment]
Yes indeed it is the problem, well spotted.

The issue is that 'global' is a singleton and when the asynchronous query handling has been implemented (previously it was synchronous), the singleton has been overlooked, hence the bug you identified. What is needed is to change property passing for  asynchronous querying. I think this change might require changes in the way a service method is invoked and how the result format is encoded to ensure isolation of query processings.
