### ISSUE TITLE
Ethercis DB connection exception after automatic update of Postgres

### ISSUE THREAD

**Issue by dileep-ehr** [ethercis/ethercis#196]
We have set up our Ubuntu server for automatic security updates. Whenever Postgres is updated (and possibly the DB server restarted), we get a DB connection exception and Ethercis stops responding. We  have to restart Ethercis to get the it working again. 

The relevant snippet of server logs attached. At 2019-08-10T15:04:07 the call is successful and at 2019-08-10T15:04:28 it starts throwing exception.
--------------------------------------
2019-08-10T15:04:07,416 | INFO  | com.ethercis.logonservice.session.SessionManager |  | Successful login for client /node/ehrserver/client/ehrnetwork/-44, session expires after [ 30 min 0 millis ], 1 of 400 sessions are in use.
2019-08-10T15:04:07,416 | INFO  | com.ethercis.logonservice.session.SessionManager |  | Client maps, sessionInfoMap.size()=1 and loginNameSubjectInfoMap.size()=1
2019-08-10T15:04:07,417 | INFO  | com.ethercis.vehr.AccessLog |  | USER[SHIRO]_ehrnetwork:post:rest/v1/session
2019-08-10T15:04:07,475 | INFO  | com.ethercis.vehr.AccessLog |  | userId=USER[SHIRO]_ehrnetwork,method=post,path=rest/v1/ehr,qryparams={subjectNamespace=ehr.network.personId;SecretSessionId=sessionId:127.0.1.1-ehrnetwork-1565429647415--730137558-45;x-client-ip=127.0.0.1;subjectId=586df605-85fe-4a3c-873d-a4aa849483d6;}
2019-08-10T15:04:07,476 | WARN  | com.ethercis.vehr.RequestDispatcher |  | Invocation exception to method:create
org.jooq.exception.DataAccessException: SQL [select 1 as "one" where exists (select 1 as "one" from "ehr"."party_identified" where ("ehr"."party_identified"."party_ref_namespace" = ? and "ehr"."party_identified"."party_ref_value" = ?))]; FATAL: terminating connection due to administrator command
at org.jooq_3.10.0.POSTGRES.debug(Unknown Source) ~[?:?]
at org.jooq.impl.Tools.translate(Tools.java:2199) ~[ecis-ehrdao-1.2.0-SNAPSHOT.jar:?]
at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:677) ~[ecis-ehrdao-1.2.0-SNAPSHOT.jar:?]
at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:358) ~[ecis-ehrdao-1.2.0-SNAPSHOT.jar:?]
at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:377) ~[ecis-ehrdao-1.2.0-SNAPSHOT.jar:?]
at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:364) ~[ecis-ehrdao-1.2.0-SNAPSHOT.jar:?]
at org.jooq.impl.AbstractResultQuery.fetchOne(AbstractResultQuery.java:529) ~[ecis-ehrdao-1.2.0-SNAPSHOT.jar:?]
at org.jooq.impl.SelectImpl.fetchOne(SelectImpl.java:2767) ~[ecis-ehrdao-1.2.0-SNAPSHOT.jar:?]
at org.jooq.impl.DefaultDSLContext.fetchExists(DefaultDSLContext.java:4019) ~[ecis-ehrdao-1.2.0-SNAPSHOT.jar:?]
at org.jooq.impl.DefaultDSLContext.fetchExists(DefaultDSLContext.java:4029) ~[ecis-ehrdao-1.2.0-SNAPSHOT.jar:?]
at com.ethercis.dao.access.jooq.PartyIdentifiedAccess.findReferencedParty(PartyIdentifiedAccess.java:303) ~[ecis-ehrdao-1.2.0-SNAPSHOT.jar:?]
at com.ethercis.dao.access.jooq.PartyIdentifiedAccess.getOrCreateParty(PartyIdentifiedAccess.java:387) ~[ecis-ehrdao-1.2.0-SNAPSHOT.jar:?]
at com.ethercis.dao.access.interfaces.I_PartyIdentifiedAccess.getOrCreatePartyByExternalRef(I_PartyIdentifiedAccess.java:182) ~[ecis-ehrdao-1.2.0-SNAPSHOT.jar:?]
at com.ethercis.persistence.AuditSetter.getCommitter(AuditSetter.java:80) ~[ecis-resource-access-service-1.2.0-SNAPSHOT.jar:?]
at com.ethercis.persistence.AuditSetter.handleProperties(AuditSetter.java:70) ~[ecis-resource-access-service-1.2.0-SNAPSHOT.jar:?]
at com.ethercis.persistence.ServiceDataCluster.queryProlog(ServiceDataCluster.java:88) ~[ecis-resource-access-service-1.2.0-SNAPSHOT.jar:?]
at com.ethercis.ehrservice.EhrService.create(EhrService.java:252) ~[ecis-ehr-service-1.2.0-SNAPSHOT.jar:?]
at sun.reflect.GeneratedMethodAccessor1027.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]
at com.ethercis.vehr.RequestDispatcher.dispatch(RequestDispatcher.java:648) [ecis-vehr-service-1.2.0-SNAPSHOT.jar:?]
at com.ethercis.vehr.RequestDispatcher.dispatch(RequestDispatcher.java:685) [ecis-vehr-service-1.2.0-SNAPSHOT.jar:?]
at com.ethercis.vehr.AccessGateService.queryHandler(AccessGateService.java:196) [ecis-vehr-service-1.2.0-SNAPSHOT.jar:?]
at com.ethercis.vehr.VEhrGateServlet.syncExecute(VEhrGateServlet.java:648) [ecis-vehr-service-1.2.0-SNAPSHOT.jar:?]
at com.ethercis.vehr.VEhrGateServlet.processRequest(VEhrGateServlet.java:626) [ecis-vehr-service-1.2.0-SNAPSHOT.jar:?]
at com.ethercis.vehr.VEhrGateServlet.doPost(VEhrGateServlet.java:469) [ecis-vehr-service-1.2.0-SNAPSHOT.jar:?]
at javax.servlet.http.HttpServlet.service(HttpServlet.java:707) [ecis-knowledge-service-1.2.0-SNAPSHOT.jar:?]
at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [ecis-knowledge-service-1.2.0-SNAPSHOT.jar:?]
at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:865) [ecis-vehr-service-1.2.0-SNAPSHOT.jar:?]
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1655) [ecis-vehr-service-1.2.0-SNAPSHOT.jar:?]
at org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:311) [ecis-vehr-service-1.2.0-SNAPSHOT.jar:?]
at org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:265) [ecis-vehr-service-1.2.0-SNAPSHOT.jar:?]
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642) [ecis-vehr-service-1.2.0-SNAPSHOT.jar:?]
at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533) [ecis-vehr-service-1.2.0-SNAPSHOT.jar:?]
at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255) [ecis-vehr-service-1.2.0-SNAPSHOT.jar:?]
at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253) [ecis-vehr-service-1.2.0-SNAPSHOT.jar:?]
at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203) [ecis-vehr-service-1.2.0-SNAPSHOT.jar:?]
at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473) [ecis-vehr-service-1.2.0-SNAPSHOT.jar:?]
at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201) [ecis-vehr-service-1.2.0-SNAPSHOT.jar:?]
at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155) [ecis-vehr-service-1.2.0-SNAPSHOT.jar:?]
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144) [ecis-vehr-service-1.2.0-SNAPSHOT.jar:?]
at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:61) [ecis-vehr-service-1.2.0-SNAPSHOT.jar:?]
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) [ecis-vehr-service-1.2.0-SNAPSHOT.jar:?]
at org.eclipse.jetty.server.Server.handle(Server.java:531) [ecis-vehr-service-1.2.0-SNAPSHOT.jar:?]
at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352) [ecis-vehr-service-1.2.0-SNAPSHOT.jar:?]
at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260) [ecis-vehr-service-1.2.0-SNAPSHOT.jar:?]
at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281) [ecis-vehr-service-1.2.0-SNAPSHOT.jar:?]
at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102) [ecis-vehr-service-1.2.0-SNAPSHOT.jar:?]
at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118) [ecis-vehr-service-1.2.0-SNAPSHOT.jar:?]
at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333) [ecis-vehr-service-1.2.0-SNAPSHOT.jar:?]
at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310) [ecis-vehr-service-1.2.0-SNAPSHOT.jar:?]
at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168) [ecis-vehr-service-1.2.0-SNAPSHOT.jar:?]
at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126) [ecis-vehr-service-1.2.0-SNAPSHOT.jar:?]
at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366) [ecis-vehr-service-1.2.0-SNAPSHOT.jar:?]
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:760) [ecis-vehr-service-1.2.0-SNAPSHOT.jar:?]
at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:678) [ecis-vehr-service-1.2.0-SNAPSHOT.jar:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
Caused by: org.postgresql.util.PSQLException: FATAL: terminating connection due to administrator command
at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2182) ~[ecis-ehrdao-1.2.0-SNAPSHOT.jar:?]
at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1911) ~[ecis-ehrdao-1.2.0-SNAPSHOT.jar:?]
at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:173) ~[ecis-ehrdao-1.2.0-SNAPSHOT.jar:?]
at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:616) ~[ecis-ehrdao-1.2.0-SNAPSHOT.jar:?]
at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:466) ~[ecis-ehrdao-1.2.0-SNAPSHOT.jar:?]
at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:459) ~[ecis-ehrdao-1.2.0-SNAPSHOT.jar:?]
at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:206) ~[ecis-ehrdao-1.2.0-SNAPSHOT.jar:?]
at org.jooq.impl.Tools.executeStatementAndGetFirstResultSet(Tools.java:3221) ~[ecis-ehrdao-1.2.0-SNAPSHOT.jar:?]
at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:259) ~[ecis-ehrdao-1.2.0-SNAPSHOT.jar:?]
at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:344) ~[ecis-ehrdao-1.2.0-SNAPSHOT.jar:?]
... 53 more
2019-08-10T15:04:07,478 | INFO  | com.ethercis.vehr.VEhrGateServlet |  | Error trapped:#1.0.0 Invocation exception to method:create:org.jooq.exception.DataAccessException: SQL [select 1 as "one" where exists (select 1 as "one" from "ehr"."party_identified" where ("ehr"."party_identified"."party_ref_namespace" = ? and "ehr"."party_identified"."party_ref_value" = ?))]; FATAL: terminating connection due to administrator command
2019-08-10T15:04:28,283 | INFO  | com.ethercis.vehr.AccessLog |  | userId=USER[SHIRO]_ehrnetwork,method=post,path=rest/v1/ehr,qryparams={subjectNamespace=ehr.network.personId;SecretSessionId=sessionId:127.0.1.1-ehrnetwork-1565429647415--730137558-45;x-client-ip=127.0.0.1;subjectId=1c85c435-26d1-4163-a413-2c80767c945f;}
2019-08-10T15:04:28,284 | WARN  | com.ethercis.vehr.RequestDispatcher |  | Invocation exception to method:create
org.jooq.exception.DataAccessException: SQL [select 1 as "one" where exists (select 1 as "one" from "ehr"."party_identified" where ("ehr"."party_identified"."party_ref_namespace" = ? and "ehr"."party_identified"."party_ref_value" = ?))]; This connection has been closed.
at org.jooq_3.10.0.POSTGRES.debug(Unknown Source) ~[?:?]
at org.jooq.impl.Tools.translate(Tools.java:2199) ~[ecis-ehrdao-1.2.0-SNAPSHOT.jar:?]
at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:677) ~[ecis-ehrdao-1.2.0-SNAPSHOT.jar:?]
at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:358) ~[ecis-ehrdao-1.2.0-SNAPSHOT.jar:?]
at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:377) ~[ecis-ehrdao-1.2.0-SNAPSHOT.jar:?]
at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:364) ~[ecis-ehrdao-1.2.0-SNAPSHOT.jar:?]
at org.jooq.impl.AbstractResultQuery.fetchOne(AbstractResultQuery.java:529) ~[ecis-ehrdao-1.2.0-SNAPSHOT.jar:?]
at org.jooq.impl.SelectImpl.fetchOne(SelectImpl.java:2767) ~[ecis-ehrdao-1.2.0-SNAPSHOT.jar:?]
at org.jooq.impl.DefaultDSLContext.fetchExists(DefaultDSLContext.java:4019) ~[ecis-ehrdao-1.2.0-SNAPSHOT.jar:?]
at org.jooq.impl.DefaultDSLContext.fetchExists(DefaultDSLContext.java:4029) ~[ecis-ehrdao-1.2.0-SNAPSHOT.jar:?]
at com.ethercis.dao.access.jooq.PartyIdentifiedAccess.findReferencedParty(PartyIdentifiedAccess.java:303) ~[ecis-ehrdao-1.2.0-SNAPSHOT.jar:?]
at com.ethercis.dao.access.jooq.PartyIdentifiedAccess.getOrCreateParty(PartyIdentifiedAccess.java:387) ~[ecis-ehrdao-1.2.0-SNAPSHOT.jar:?]
at com.ethercis.dao.access.interfaces.I_PartyIdentifiedAccess.getOrCreatePartyByExternalRef(I_PartyIdentifiedAccess.java:182) ~[ecis-ehrdao-1.2.0-SNAPSHOT.jar:?]
at com.ethercis.persistence.AuditSetter.getCommitter(AuditSetter.java:80) ~[ecis-resource-access-service-1.2.0-SNAPSHOT.jar:?]
at com.ethercis.persistence.AuditSetter.handleProperties(AuditSetter.java:70) ~[ecis-resource-access-service-1.2.0-SNAPSHOT.jar:?]
at com.ethercis.persistence.ServiceDataCluster.queryProlog(ServiceDataCluster.java:88) ~[ecis-resource-access-service-1.2.0-SNAPSHOT.jar:?]
at com.ethercis.ehrservice.EhrService.create(EhrService.java:252) ~[ecis-ehr-service-1.2.0-SNAPSHOT.jar:?]
at sun.reflect.GeneratedMethodAccessor1027.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]
at com.ethercis.vehr.RequestDispatcher.dispatch(RequestDispatcher.java:648) [ecis-vehr-service-1.2.0-SNAPSHOT.jar:?]
at com.ethercis.vehr.RequestDispatcher.dispatch(RequestDispatcher.java:685) [ecis-vehr-service-1.2.0-SNAPSHOT.jar:?]
at com.ethercis.vehr.AccessGateService.queryHandler(AccessGateService.java:196) [ecis-vehr-service-1.2.0-SNAPSHOT.jar:?]
at com.ethercis.vehr.VEhrGateServlet.syncExecute(VEhrGateServlet.java:648) [ecis-vehr-service-1.2.0-SNAPSHOT.jar:?]
at com.ethercis.vehr.VEhrGateServlet.processRequest(VEhrGateServlet.java:626) [ecis-vehr-service-1.2.0-SNAPSHOT.jar:?]
at com.ethercis.vehr.VEhrGateServlet.doPost(VEhrGateServlet.java:469) [ecis-vehr-service-1.2.0-SNAPSHOT.jar:?]
at javax.servlet.http.HttpServlet.service(HttpServlet.java:707) [ecis-knowledge-service-1.2.0-SNAPSHOT.jar:?]
at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [ecis-knowledge-service-1.2.0-SNAPSHOT.jar:?]
at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:865) [ecis-vehr-service-1.2.0-SNAPSHOT.jar:?]
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1655) [ecis-vehr-service-1.2.0-SNAPSHOT.jar:?]
at org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:311) [ecis-vehr-service-1.2.0-SNAPSHOT.jar:?]
at org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:265) [ecis-vehr-service-1.2.0-SNAPSHOT.jar:?]
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642) [ecis-vehr-service-1.2.0-SNAPSHOT.jar:?]
at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533) [ecis-vehr-service-1.2.0-SNAPSHOT.jar:?]
at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255) [ecis-vehr-service-1.2.0-SNAPSHOT.jar:?]
at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253) [ecis-vehr-service-1.2.0-SNAPSHOT.jar:?]
at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203) [ecis-vehr-service-1.2.0-SNAPSHOT.jar:?]
at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473) [ecis-vehr-service-1.2.0-SNAPSHOT.jar:?]
at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201) [ecis-vehr-service-1.2.0-SNAPSHOT.jar:?]
at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155) [ecis-vehr-service-1.2.0-SNAPSHOT.jar:?]
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144) [ecis-vehr-service-1.2.0-SNAPSHOT.jar:?]
at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:61) [ecis-vehr-service-1.2.0-SNAPSHOT.jar:?]
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) [ecis-vehr-service-1.2.0-SNAPSHOT.jar:?]
at org.eclipse.jetty.server.Server.handle(Server.java:531) [ecis-vehr-service-1.2.0-SNAPSHOT.jar:?]
at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352) [ecis-vehr-service-1.2.0-SNAPSHOT.jar:?]
at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260) [ecis-vehr-service-1.2.0-SNAPSHOT.jar:?]
at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281) [ecis-vehr-service-1.2.0-SNAPSHOT.jar:?]
at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102) [ecis-vehr-service-1.2.0-SNAPSHOT.jar:?]
at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118) [ecis-vehr-service-1.2.0-SNAPSHOT.jar:?]
at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333) [ecis-vehr-service-1.2.0-SNAPSHOT.jar:?]
at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310) [ecis-vehr-service-1.2.0-SNAPSHOT.jar:?]
at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168) [ecis-vehr-service-1.2.0-SNAPSHOT.jar:?]
at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126) [ecis-vehr-service-1.2.0-SNAPSHOT.jar:?]
at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366) [ecis-vehr-service-1.2.0-SNAPSHOT.jar:?]
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:760) [ecis-vehr-service-1.2.0-SNAPSHOT.jar:?]
at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:678) [ecis-vehr-service-1.2.0-SNAPSHOT.jar:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
Caused by: org.postgresql.util.PSQLException: This connection has been closed.
at org.postgresql.jdbc2.AbstractJdbc2Connection.checkClosed(AbstractJdbc2Connection.java:861) ~[ecis-ehrdao-1.2.0-SNAPSHOT.jar:?]
at org.postgresql.jdbc3.AbstractJdbc3Connection.prepareStatement(AbstractJdbc3Connection.java:281) ~[ecis-ehrdao-1.2.0-SNAPSHOT.jar:?]
at org.postgresql.jdbc2.AbstractJdbc2Connection.prepareStatement(AbstractJdbc2Connection.java:334) ~[ecis-ehrdao-1.2.0-SNAPSHOT.jar:?]
at org.jooq.impl.ProviderEnabledConnection.prepareStatement(ProviderEnabledConnection.java:106) ~[ecis-ehrdao-1.2.0-SNAPSHOT.jar:?]
at org.jooq.impl.SettingsEnabledConnection.prepareStatement(SettingsEnabledConnection.java:70) ~[ecis-ehrdao-1.2.0-SNAPSHOT.jar:?]
at org.jooq.impl.AbstractResultQuery.prepare(AbstractResultQuery.java:230) ~[ecis-ehrdao-1.2.0-SNAPSHOT.jar:?]
at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:316) ~[ecis-ehrdao-1.2.0-SNAPSHOT.jar:?]
... 53 more
-------------------------------------------------------------

**Comment by chevalleyc** [comment]
To deal with this issue, I would suggest to migrate on 1.3 and use DBPC2

**Comment by dileep-ehr** [comment]
Thanks. Does 1.3 use DBCP2 by default or do we need to do anything
additional to use it

Regards

**Comment by chevalleyc** [comment]
By default, 1.3 uses JDBC, to configure the instance to use DBCP2, you'll need to set services.properties (https://github.com/ethercis/deploy-n-scripts/blob/master/ethercis-install/v1.3.0/config/services.properties) section #this configuration uses DBCP2 (uncomment the first paragraph and comment the JDBC part above)

**Comment by dileep-ehr** [comment]
Thank you
