### ISSUE TITLE
Error running 'populate-concept' script

### ISSUE THREAD

**Issue by dileep-ehr** [ethercis/ethercis#36]
While running the populate-concept script to setup Ethercis from uberjars on Ubuntu 16.04, i get the following error
```
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.
Exception in thread "main" java.lang.NoClassDefFoundError: com/ethercis/jooq/pg/Tables
	at com.ethercis.dao.access.support.TerminologySetter.createTerminologyTables(TerminologySetter.java:128)
	at com.ethercis.dao.access.support.TerminologySetter.main(TerminologySetter.java:423)
Caused by: java.lang.ClassNotFoundException: com.ethercis.jooq.pg.Tables
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 2 more
```
I am unable to find the problem. The concept table seems to have been populated with some values and the server starts and runs normally. While most of the things seem to work, I am not sure that everything is set up properly.  

How can I verify if everything is setup properly?

**Comment by dileep-ehr** [comment]
I have managed to fix this. The populate-concept was missing 'jooq-pg-1.1.0-SNAPSHOT.jar' in CLASSPATH. After that was added, the script runs OK
