### ISSUE TITLE
Cannot load QueryService

### ISSUE THREAD

**Issue by donkariro** [ethercis/ethercis#75]
I have been trying to execute the Ethercis application from the Launcher mainclass but keep getting the error below. Any help will be highly appreciated. thank you:

===========================================================================
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Property: could not find default property file, will try from command line arguments
Property: No args array given.
Property: File 'services.properties' not found
Property: Loading /home/donkariro/ETHERCIS/services.properties from directory /home/donkariro/ETHERCIS/VirtualEhr
ClusterController ERROR: errorCode=resource.configuration message=#1.0.0 Unknown variable ${jooq.dialect}
log4j:WARN No appenders could be found for logger (org.springframework.core.env.StandardEnvironment).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
19:23:28.072 [main] ERROR com.ethercis.servicemanager.cluster.ClusterInfo - Unable to load service identified as:QueryService,0.1. Please check your code...
19:23:28.074 [main] ERROR com.ethercis.vehr.VEhrGateServlet - ServiceManagerException errorCode=[resource.configuration.serviceFailed] location=[RunlevelManager.startupServices] message=[#1.0.0 Can't load plugin 'RequestDispatcher']
19:23:28.074 [main] ERROR com.ethercis.vehr.VEhrGateServlet - Changing runlevel to 'RUNNING' failed, good bye
errorCode=user.configuration message=#1.0.0 The runtimeservice could not be found:QueryService,0.1, path:
	at com.ethercis.vehr.RequestDispatcher$ServiceAttribute.<init>(RequestDispatcher.java:194)
	at com.ethercis.vehr.QuerySyntaxMapper.loadConfiguration(QuerySyntaxMapper.java:82)
	at com.ethercis.vehr.RequestDispatcher.doInit(RequestDispatcher.java:585)
	at com.ethercis.servicemanager.cluster.ClusterInfo.init(ClusterInfo.java:347)
	at com.ethercis.servicemanager.service.ServiceManagerBase.instantiateServiceSecondPhase(ServiceManagerBase.java:293)
	at com.ethercis.servicemanager.service.ServiceManagerBase.getServiceObject(ServiceManagerBase.java:126)
	at com.ethercis.servicemanager.runlevel.RunlevelManager.startupServices(RunlevelManager.java:360)
	at com.ethercis.servicemanager.runlevel.RunlevelManager.changeRunlevel(RunlevelManager.java:278)
	at com.ethercis.vehr.VEhrGateServlet.init(VEhrGateServlet.java:236)
	at com.ethercis.vehr.Launcher.start(Launcher.java:108)
	at com.ethercis.vehr.Launcher.startServer(Launcher.java:77)
	at com.ethercis.vehr.Launcher.main(Launcher.java:194)
Exception in thread "Signal catcher thread for controlled shudown" java.lang.NullPointerException
	at com.ethercis.vehr.VEhrGateServlet.destroy(VEhrGateServlet.java:285)
	at com.ethercis.vehr.VEhrGateServlet.shutdownHook(VEhrGateServlet.java:435)
	at com.ethercis.servicemanager.cluster.SignalCatcher.run(SignalCatcher.java:216)
	at java.lang.Thread.run(Thread.java:745)

**Comment by chevalleyc** [comment]
It seems to me that there are a lot of issues in your ethercis deployment (classpath is definitely wrong as it looks). I will post very soon a set of install scripts as well as a release archive to help in the process of installing EtherCIS. In the meantime, please check your classpath declaration in your startup script. Thanks

**Comment by donkariro** [comment]
Thank you very much Chris for your response. Actually, I am not deploying Ethercis using your bash script. I have assembled the libraries and configuration files in a directory and I am now trying to run it using the Launcher main-class. I will re-check my classpath

**Comment by chevalleyc** [comment]
Potentially solved by using the correct install script.
